<a href="https://colab.research.google.com/github/devanomaly/tensorflow-stuff/blob/main/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental stuff with tensors in tensorflow

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (way to speed up regular Python functions)
* Using GPUs with TF (or TPUs)
* Exercises

In [4]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [5]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
scalar.ndim

0

In [8]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
vector.ndim

1

In [12]:
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [13]:
matrix.ndim

2

In [22]:
tetrix = tf.constant([[[1,2],[3,4]],[[1,2],[3,4]]], dtype=tf.float64)
tetrix

<tf.Tensor: shape=(2, 2, 2), dtype=float64, numpy=
array([[[1., 2.],
        [3., 4.]],

       [[1., 2.],
        [3., 4.]]])>

In [23]:
tetrix.ndim

3

In [24]:
tensor = tf.constant([[[1,2,3,],[4,5,6]],[[1,2,3,],[4,5,6]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [25]:
tensor.ndim

3

# Now let us see another way to create tensors

In [35]:
varTensor = tf.Variable([10,7])
varTensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [36]:
varTensor[1].assign(1000)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([  10, 1000], dtype=int32)>

# Creating random tensors

In [38]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(2,2))
random_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [45]:
random_2 = tf.random.Generator.from_seed(42).uniform(shape=(2,2))
random_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817]], dtype=float32)>

### Shuffle the order of elements in a tensor

In [47]:
# Shuffle a tensor 
unshuffled = tf.constant([[1,2], [3,4],[5,6]])
unshuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [81]:
shuffled = tf.random.shuffle(unshuffled)
transposedShuffle = tf.transpose(tf.random.shuffle(tf.transpose(unshuffled)))
print(shuffled)
transposedShuffle

tf.Tensor(
[[3 4]
 [5 6]
 [1 2]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [4, 3],
       [6, 5]], dtype=int32)>

### Other ways to make tensors

In [85]:
tf.ones([3,5]) #shape=(3,5)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [86]:
tf.zeros([10,2])

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

### One might turn numpy arrays into tf tensors

Main difference? Tensors (tf tensors, but I'll omit "tf" whenever it's subintended) can be run on a GPU -- much faster for numerical computing.

In [105]:
import numpy as np
numpy_A = np.arange(0,42, dtype=np.float64)

In [106]:
A1 = tf.constant([numpy_A, numpy_A], dtype=tf.float64)
A2 = tf.constant([numpy_A, numpy_A], shape=(7,3,4),dtype=tf.float64)

print(A1)
print(A2)

tf.Tensor(
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36. 37. 38. 39. 40. 41.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36. 37. 38. 39. 40. 41.]], shape=(2, 42), dtype=float64)
tf.Tensor(
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]

 [[24. 25. 26. 27.]
  [28. 29. 30. 31.]
  [32. 33. 34. 35.]]

 [[36. 37. 38. 39.]
  [40. 41.  0.  1.]
  [ 2.  3.  4.  5.]]

 [[ 6.  7.  8.  9.]
  [10. 11. 12. 13.]
  [14. 15. 16. 17.]]

 [[18. 19. 20. 21.]
  [22. 23. 24. 25.]
  [26. 27. 28. 29.]]

 [[30. 31. 32. 33.]
  [34. 35. 36. 37.]
  [38. 39. 40. 41.]]], shape=(7, 3, 4), dtype=float64)


In [107]:
A1.ndim

2

In [108]:
A2.ndim

3

### Getting more information from tensors
Important attributes
* Shape
* Rank
* Axis/dimension
* Size

In [114]:
rank4 = tf.zeros(shape=[2,3,4,5])

In [115]:
rank4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [116]:
rank4.shape, tf.size(rank4), rank4.ndim

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>, 4)

In [118]:
print("Datatype", rank4.dtype)
print("Rank", rank4.ndim)
print("Shape", rank4.shape)
print("# of elements", tf.size(rank4))
print("# of elements", tf.size(rank4).numpy())


Datatype <dtype: 'float32'>
Rank 4
Shape (2, 3, 4, 5)
# of elements tf.Tensor(120, shape=(), dtype=int32)
# of elements 120


### Indexing tensors
Just like Python lists

In [126]:
# Get the first 2 elements of each dimension
print(rank4[:2, :2, :2, :2])

tf.Tensor(
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]], shape=(2, 2, 2, 2), dtype=float32)


In [127]:
# Get the first element from each dimension from each index except for the final one
rank4[0,0,0] # (or rank4[:1, :1, :1], but shape is different!)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [132]:
rank2 = tf.constant([[1,2], [3,4]])

In [133]:
rank2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [134]:
rank2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [142]:
# Add in extra dimension to our rank 2 tensor
rank3 = rank2[tf.newaxis, ...] # expand first axis
print("extra dim at beginning\n", rank3)
rank3 = rank2[..., tf.newaxis] # expand last axis
print("\nextra dim at end\n", rank3)



extra dim at beginning
 tf.Tensor(
[[[1 2]
  [3 4]]], shape=(1, 2, 2), dtype=int32)

extra dim at end
 tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


In [138]:
# Alternative to tf.newaxis
tf.expand_dims(rank2, axis=-1) # -1 => expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>