<a href="https://colab.research.google.com/github/devanomaly/tensorflow-stuff/blob/main/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental stuff with tensors in tensorflow

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (way to speed up regular Python functions)
* Using GPUs with TF (or TPUs)
* Exercises

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
tetrix = tf.constant([[[1,2],[3,4]],[[1,2],[3,4]]], dtype=tf.float64)
tetrix

<tf.Tensor: shape=(2, 2, 2), dtype=float64, numpy=
array([[[1., 2.],
        [3., 4.]],

       [[1., 2.],
        [3., 4.]]])>

In [ ]:
tetrix.ndim

3

In [ ]:
tensor = tf.constant([[[1,2,3,],[4,5,6]],[[1,2,3,],[4,5,6]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# Now let us see another way to create tensors

In [ ]:
varTensor = tf.Variable([10,7])
varTensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
varTensor[1].assign(1000)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([  10, 1000], dtype=int32)>

# Creating random tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(2,2))
random_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42).uniform(shape=(2,2))
random_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817]], dtype=float32)>

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor 
unshuffled = tf.constant([[1,2], [3,4],[5,6]])
unshuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
shuffled = tf.random.shuffle(unshuffled)
transposedShuffle = tf.transpose(tf.random.shuffle(tf.transpose(unshuffled)))
print(shuffled)
transposedShuffle

tf.Tensor(
[[5 6]
 [1 2]
 [3 4]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

### Other ways to make tensors

In [ ]:
tf.ones([3,5]) #shape=(3,5)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([10,2])

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

### One might turn numpy arrays into tf tensors

Main difference? Tensors (tf tensors, but I'll omit "tf" whenever it's subintended) can be run on a GPU -- much faster for numerical computing.

In [ ]:
import numpy as np
numpy_A = np.arange(0,42, dtype=np.float64)

In [ ]:
A1 = tf.constant([numpy_A, numpy_A], dtype=tf.float64)
A2 = tf.constant([numpy_A, numpy_A], shape=(7,3,4),dtype=tf.float64)

print(A1)
print(A2)

tf.Tensor(
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36. 37. 38. 39. 40. 41.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36. 37. 38. 39. 40. 41.]], shape=(2, 42), dtype=float64)
tf.Tensor(
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]

 [[24. 25. 26. 27.]
  [28. 29. 30. 31.]
  [32. 33. 34. 35.]]

 [[36. 37. 38. 39.]
  [40. 41.  0.  1.]
  [ 2.  3.  4.  5.]]

 [[ 6.  7.  8.  9.]
  [10. 11. 12. 13.]
  [14. 15. 16. 17.]]

 [[18. 19. 20. 21.]
  [22. 23. 24. 25.]
  [26. 27. 28. 29.]]

 [[30. 31. 32. 33.]
  [34. 35. 36. 37.]
  [38. 39. 40. 41.]]], shape=(7, 3, 4), dtype=float64)


In [ ]:
A1.ndim

2

In [ ]:
A2.ndim

3

### Getting more information from tensors
Important attributes
* Shape
* Rank
* Axis/dimension
* Size

In [ ]:
rank4 = tf.zeros(shape=[2,3,4,5])

In [ ]:
rank4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4.shape, tf.size(rank4), rank4.ndim

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>, 4)

In [ ]:
print("Datatype", rank4.dtype)
print("Rank", rank4.ndim)
print("Shape", rank4.shape)
print("# of elements", tf.size(rank4))
print("# of elements", tf.size(rank4).numpy())


Datatype <dtype: 'float32'>
Rank 4
Shape (2, 3, 4, 5)
# of elements tf.Tensor(120, shape=(), dtype=int32)
# of elements 120


### Indexing tensors
Just like Python lists

In [ ]:
# Get the first 2 elements of each dimension
print(rank4[:2, :2, :2, :2])

tf.Tensor(
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]], shape=(2, 2, 2, 2), dtype=float32)


In [ ]:
# Get the first element from each dimension from each index except for the final one
rank4[0,0,0] # (or rank4[:1, :1, :1], but shape is different!)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
rank2 = tf.constant([[1,2], [3,4]])

In [ ]:
rank2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
rank2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank3 = rank2[tf.newaxis, ...] # expand first axis
print("extra dim at beginning\n", rank3)
rank3 = rank2[..., tf.newaxis] # expand last axis
print("\nextra dim at end\n", rank3)



extra dim at beginning
 tf.Tensor(
[[[1 2]
  [3 4]]], shape=(1, 2, 2), dtype=int32)

extra dim at end
 tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank2, axis=-1) # -1 => expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

### Tensor operations
**Basic operations**

`+`, `-`, `*`, `/`

In [ ]:
tensor1 = tf.constant([[1,2], [3,4]])
print(tensor1)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
print(tensor1 + 10)

tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)


In [ ]:
print(tensor1*10)

tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [ ]:
# we can use tensorflow functions (these optimize computing with G/TPU)
tf.multiply(tensor1,10) #leaves tensor1 unaltered

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

### **Matrix multiplication**

In [ ]:
tf.matmul(tensor1,tensor1) # usual matrix mult (traced/contracted dimensions must match size)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
print(tensor1 * tensor1) # element-wise mult
#To do usual matrix mult with Python, use "@" operator
print(tensor1@tensor1)

tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


### Tensor Aggregation

In [ ]:
# Get the absolute values
D = tf.constant([-1,-2])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
D = tf.constant(np.random.randint(0,100, size=30))
D

<tf.Tensor: shape=(30,), dtype=int64, numpy=
array([ 6, 22, 28,  4, 70, 37, 73, 42, 52, 92, 13, 80, 95,  5, 76, 34, 91,
       66, 54, 73, 30, 16, 65, 98, 34, 62, 10,  1, 52, 78])>

In [ ]:
tf.size(D), D.shape, D.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=30>, TensorShape([30]), 1)

In [ ]:
#Find the minimum
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
#Find the maximum
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find the mean
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
#Find the sum
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int64, numpy=1459>

In [ ]:
# Find the variance (defaults over all dimensions... one might select axis as well)
var=tf.math.reduce_variance(tf.cast(D, tf.float32))
var

<tf.Tensor: shape=(), dtype=float32, numpy=906.699>

In [ ]:
# Standard deviation (STD) from squareroot of var
std=var**.5
std

<tf.Tensor: shape=(), dtype=float32, numpy=30.111443>

In [ ]:
# STD from tf reduce
tfSTD = tf.math.reduce_std(tf.cast(D, tf.float32))
tfSTD

<tf.Tensor: shape=(), dtype=float32, numpy=30.111443>

### Find positional maximum and find positional minimum

In [ ]:
tf.argmax(D)

<tf.Tensor: shape=(), dtype=int64, numpy=23>

In [ ]:
tf.argmin(D)

<tf.Tensor: shape=(), dtype=int64, numpy=27>

In [ ]:
D[23]

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
D[27]

<tf.Tensor: shape=(), dtype=int64, numpy=1>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
G = tf.constant(tf.random.normal(shape=[100]), shape=(1,1,1,1,100))
G

<tf.Tensor: shape=(1, 1, 1, 1, 100), dtype=float32, numpy=
array([[[[[-0.6843161 ,  0.23483357,  0.6483124 , -1.1318921 ,
            0.35062066, -0.44171876,  1.3780015 ,  0.03439614,
            0.961923  , -0.75962985,  0.46549132,  0.05181826,
            0.29722807,  2.0745263 , -0.6539294 , -1.0487171 ,
            0.83192664,  0.74256605,  0.8534327 , -1.4534191 ,
           -0.1259824 ,  0.01822014,  1.423327  ,  1.4313924 ,
            0.23450111, -0.5545286 ,  0.16353711,  0.7549506 ,
           -0.0530722 ,  2.5803587 ,  1.8475969 , -1.6993229 ,
           -0.21826038, -1.9790648 ,  1.3239477 , -0.4986821 ,
           -0.68280977, -0.8570898 ,  1.2765492 ,  0.26209712,
           -0.7384397 , -1.5965741 , -1.3743446 , -0.64651686,
            1.2102265 , -1.6637774 , -0.44633752, -1.420321  ,
            0.8376473 , -0.20097737, -1.7677922 ,  1.4593617 ,
            0.8965035 , -1.1544554 , -0.2997026 ,  0.6084455 ,
           -0.9476956 ,  0.41863286, -0.80127114, -1.119901

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 100])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([-0.6843161 ,  0.23483357,  0.6483124 , -1.1318921 ,  0.35062066,
       -0.44171876,  1.3780015 ,  0.03439614,  0.961923  , -0.75962985,
        0.46549132,  0.05181826,  0.29722807,  2.0745263 , -0.6539294 ,
       -1.0487171 ,  0.83192664,  0.74256605,  0.8534327 , -1.4534191 ,
       -0.1259824 ,  0.01822014,  1.423327  ,  1.4313924 ,  0.23450111,
       -0.5545286 ,  0.16353711,  0.7549506 , -0.0530722 ,  2.5803587 ,
        1.8475969 , -1.6993229 , -0.21826038, -1.9790648 ,  1.3239477 ,
       -0.4986821 , -0.68280977, -0.8570898 ,  1.2765492 ,  0.26209712,
       -0.7384397 , -1.5965741 , -1.3743446 , -0.64651686,  1.2102265 ,
       -1.6637774 , -0.44633752, -1.420321  ,  0.8376473 , -0.20097737,
       -1.7677922 ,  1.4593617 ,  0.8965035 , -1.1544554 , -0.2997026 ,
        0.6084455 , -0.9476956 ,  0.41863286, -0.80127114, -1.1199018 ,
       -0.2491907 ,  0.07086425, -1.4630448 , -0.42115992, -0.07255735,
       -2.728572

### One-hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0,1,2,3] 

# One-hot encode our list of indices
tf.one_hot(some_list, len(some_list)-1)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

### More maths with tensors

In [ ]:
H = tf.constant([range(1,50),range(1,50)])
H

<tf.Tensor: shape=(2, 49), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49]], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(2, 49), dtype=int32, numpy=
array([[   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
         144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
         529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
        1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
        2025, 2116, 2209, 2304, 2401],
       [   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
         144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
         529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
        1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
        2025, 2116, 2209, 2304, 2401]], dtype=int32)>

In [ ]:
H = tf.cast(H, tf.float32)

In [ ]:
tf.sqrt(H)

<tf.Tensor: shape=(2, 49), dtype=float32, numpy=
array([[0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
        2.4494896 , 2.6457512 , 2.8284268 , 2.9999998 , 3.1622777 ,
        3.3166244 , 3.4641016 , 3.6055508 , 3.7416573 , 3.8729832 ,
        3.9999998 , 4.1231055 , 4.2426405 , 4.3588986 , 4.472136  ,
        4.5825753 , 4.6904154 , 4.795831  , 4.898979  , 5.        ,
        5.0990195 , 5.196152  , 5.2915025 , 5.3851647 , 5.477226  ,
        5.5677643 , 5.6568537 , 5.744562  , 5.830951  , 5.9160795 ,
        5.9999995 , 6.0827622 , 6.164414  , 6.244997  , 6.3245554 ,
        6.4031243 , 6.4807405 , 6.557438  , 6.633249  , 6.7082043 ,
        6.78233   , 6.8556547 , 6.928203  , 6.9999995 ],
       [0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
        2.4494896 , 2.6457512 , 2.8284268 , 2.9999998 , 3.1622777 ,
        3.3166244 , 3.4641016 , 3.6055508 , 3.7416573 , 3.8729832 ,
        3.9999998 , 4.1231055 , 4.2426405 , 4.3588986 , 4.472136  ,
        4.

In [ ]:
tf.math.log(H)

<tf.Tensor: shape=(2, 49), dtype=float32, numpy=
array([[0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
        2.5649493, 2.6390574, 2.7080503, 2.7725887, 2.8332133, 2.8903718,
        2.944439 , 2.9957323, 3.0445225, 3.0910425, 3.1354942, 3.1780539,
        3.218876 , 3.2580965, 3.295837 , 3.3322046, 3.3672957, 3.4011974,
        3.4339871, 3.465736 , 3.4965076, 3.5263605, 3.5553482, 3.583519 ,
        3.610918 , 3.637586 , 3.6635616, 3.6888795, 3.713572 , 3.7376697,
        3.7612002, 3.7841897, 3.8066626, 3.8286414, 3.8501477, 3.871201 ,
        3.8918204],
       [0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
        2.5649493, 2.6390574, 2.7080503, 2.7725887, 2.8332133, 2.8903718,
        2.944439 , 2.9957323, 3.0445225, 3.0910425, 3.1354942, 3.1780539,
        3.218876 , 3.2580965, 3.295837 , 3.

### Tensors and NumPy

In [ ]:
J = tf.constant(np.array([3., 1., 7.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 1., 7.])>

In [ ]:
np.array(J)

array([3., 1., 7.])

In [ ]:
J.numpy()

array([3., 1., 7.])

In [ ]:
# The default types are slightly different
numpy_J = tf.constant(np.array([3.,1.,7.]))
tensor_J = tf.constant([3.,1.,7.])
# Check the datatypes
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Accessing GPUs

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Apr  6 19:38:53 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    30W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------