<a href="https://colab.research.google.com/github/devanomaly/tensorflow-stuff/blob/main/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental stuff with tensors in tensorflow

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (way to speed up regular Python functions)
* Using GPUs with TF (or TPUs)
* Exercises

In [4]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [5]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
scalar.ndim

0

In [8]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
vector.ndim

1

In [12]:
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [13]:
matrix.ndim

2

In [22]:
tetrix = tf.constant([[[1,2],[3,4]],[[1,2],[3,4]]], dtype=tf.float64)
tetrix

<tf.Tensor: shape=(2, 2, 2), dtype=float64, numpy=
array([[[1., 2.],
        [3., 4.]],

       [[1., 2.],
        [3., 4.]]])>

In [23]:
tetrix.ndim

3

In [24]:
tensor = tf.constant([[[1,2,3,],[4,5,6]],[[1,2,3,],[4,5,6]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [25]:
tensor.ndim

3

# Now let us see another way to create tensors

In [35]:
varTensor = tf.Variable([10,7])
varTensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [36]:
varTensor[1].assign(1000)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([  10, 1000], dtype=int32)>

# Creating random tensors